language: node_js
node_js:
- "10"
sudo: false
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"chatter_app",pwd:"chatter",roles:["readWrite"]});'
script:
- npm run lint
services:
  - mongodb
  - docker
cache:
  directories:
  - node_modules