language: node_js
node_js:
- node
sudo: false
before_script:
- mongo mydb_test --eval 'db.createUser({user:"chatter_app",pwd:"chatter",roles:["readWrite"]});'
script:
- npm run lint
services:
- mongodb
- docker
cache:
  directories:
  - node_modules
after_success:
- test $TRAVIS_BRANCH = "master" &&  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- test $TRAVIS_BRANCH = "master" && docker build -t registry.heroku.com/chatter/web .
- test $TRAVIS_BRANCH = "master" && docker push registry.heroku.com/chatter/web
