language: node_js
node_js:
- node
sudo: required
before_script:
- mongo chatter_app_test --eval 'db.createUser({user:"chatter_app_test",pwd:"test_psw",roles:["readWrite"]});'
script:
- npm run lint
services:
- mongodb
cache:
  directories:
  - node_modules
