language: node_js
node_js:
- node
sudo: false
install:
- npm i -g mocha eslint eslint-plugin-node eslint-plugin-jasmine eslint-plugin-standard
before_script:
- mongo chatter_app_test --eval 'db.createUser({user:"chatter_app_test",pwd:"test_psw",roles:["readWrite"]});'
script:
- npm run test
services:
- mongodb
cache:
  directories:
  - node_modules
