language: node_js
node_js:
- node
sudo: required
before_script:
- mongo mydb_test --eval 'db.createUser({user:"chatter_app",pwd:"chatter",roles:["readWrite"]});'
script:
- npm run lint
services:
- mongodb
cache:
  directories:
  - node_modules
